apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-starter-setting
spec:
  forms:
    - group: style
      label: 样式
      formSchema:
        - $formkit: color
          name: background_color
          label: 背景颜色
          value: "#f2f2f2"
